(function(){
  'use strict';
  var h = React.createElement;
  var useState = React.useState;
  var useEffect = React.useEffect;
  var useCallback = React.useCallback;
  var useRef = React.useRef;

  var INIT = {
    rows:25,cols:25,shape:'dragon',
    allowDiag:true,allowReverse:true,allowH:true,allowV:true,
    letterCase:'upper',fontWeight:'700',fontFamily:'Inter, sans-serif',
    showWordList:true,showPageNum:true,pageNum:1,showSolution:false,
    wordFontSize:14,wordsPerGrid:20,wordColumns:4,cellSize:24,
    title:'MXD SUPREME PUZZLE',subtitle:'',
    highlightColor:'#6c63ff',solutionStyle:'highlight',
    template:'classic',bulkMode:false,bulkPageCount:100,visualThemeId:'classic',
    pageSize:'8.5x11',orientation:'portrait',
    marginPreset:'standard',marginTop:28,marginBottom:28,marginInner:36,marginOuter:28,
    autoSplit:true,fillMissing:true,difficulty:'medium',aiOptimize:true,
    uiTheme:'day',puzzleType:'wordsearch',variation:'var_0',aiExtreme:false,
    highRes:false,svgExport:false,spyMode:false,
    showGridLines:true,bleed:0,compress:true,watermark:false,watermarkText:'Generated by MXD Word Search',kdpCompliant:true,
    titleFontSize:22,titleStyle:'plain',titleAlign:'center',titleWeight:700,titleGap:0,titleIndent:0,
    showGrid:true,seed:0,overlapPolicy:'moderate',edgeBias:'none',clustering:'none',fillerComplexity:'simple',
    customDictionary:'',excludeWords:'',
    largePrint:false,highContrast:false,dyslexiaFont:false,reducedMotion:false,screenReader:false,
    language:'en',wordListLanguage:'en',
    aiProvider:'auto',aiModel:'auto',aiTemperature:0.7,aiMaxTokens:2000,localAiEnabled:false,
    parallelWorkers:4,cacheEnabled:true,autoSave:true,autoSaveDelay:300,
    sidebarCollapsed:false,settingsModalOpen:false,
    sizeMode:'custom',autoCellSize:false,titlePos:1,
    listHeaderSize:13,gridFontSize:24,showInfo:true,showFound:true,
    wordSort:'alpha',autoFitWL:true,autoFontSize:true,
    pillFill:'#f3f4f6',pillText:'#1f2937',pillBorder:false,pillBorderColor:'#d1d5db',pillBorderW:1,pillRadius:6,pillPadX:8,pillPadY:4,
    outlineColor:'none',outlineWidth:2,shapeBg:'',
    includeCover:false,includeTOC:false,shufflePages:false,startPage:1,
    dpi:300,imageFormat:'png',jpegQuality:0.95,exportName:'',
    mkt:'us',
    placement:'balanced',overlap:'match',placeOrder:'longest',
    fillerMode:'random',strategy:'balanced',
    allowLeft:false,allowUp:false,allowDiagLeft:false,allowDiagUp:false,allowDiagUpLeft:false,
    autoRetry:true,autoSkip:false,maxRetries:50,
    visualStyle:'clean',cellShape:'square',letterMode:'random',
    playMode:'practice',clickDrag:true,showTimer:false,showHints:false,maxHints:3,autoSaveProgress:true,
    titleFontSize:20,gridFontSize:24,wordFontSize:11,listHeaderSize:13,
    titleIndent:0,titleGap:0,listIndent:0,listGap:0,
    gridSize:'15x15',wordsPerGrid:15
  };

  function parseWords(txt){ return txt.split(/[\n,]+/).map(function(w){return w.trim().replace(/[^a-zA-Z]/g,'');}).filter(function(w){return w.length>=2;}); }

  function getCellsBetween(r1,c1,r2,c2){
    var dr=r2-r1, dc=c2-c1;
    var steps=Math.max(Math.abs(dr),Math.abs(dc));
    if(steps===0) return [[r1,c1]];
    if(dr!==0 && dc!==0 && Math.abs(dr)!==Math.abs(dc)) return [];
    var sr=dr/steps, sc=dc/steps;
    return Array.from({length:steps+1},function(_,i){return [Math.round(r1+sr*i),Math.round(c1+sc*i)];});
  }

  function DragonBG() {
    return h('div', {className:'dragon-bg'},
      h('svg', {className:'dragon-silhouette', viewBox:'0 0 100 100', style:{top:'10%', left:'-10%', animationDelay:'0s'}},
        h('path', {d:'M10,50 Q25,20 40,50 T70,50 T90,30', stroke:'white', fill:'none', strokeWidth:'0.5'})
      )
    );
  }

  window.WS = window.WS || {};

  window.WS.Toast = function(props) {
    var msg = props.msg || '', type = props.type || 'info';
    if (!msg) return null;
    var colors = { success: '#059669', error: '#dc2626', warn: '#d97706', info: '#6366f1' };
    return h('div', { style: { position:'fixed', bottom:'24px', left:'50%', transform:'translateX(-50%)', padding:'10px 20px', borderRadius:'8px', fontSize:'13px', fontWeight:'600', zIndex:9999, boxShadow:'0 4px 12px rgba(0,0,0,0.15)', background: colors[type] || colors.info, color:'#fff' } }, msg);
  };

  window.WS.WordList = function(props) {
    var words = props.words || [], found = props.found || [];
    if (!words.length) return null;
    return h('div', { style: { marginTop:'12px', padding:'12px', background:'var(--bg)', borderRadius:'8px', border:'1px solid var(--border)' } },
      h('div', { style: { fontSize:'11px', fontWeight:'600', color:'var(--t2)', marginBottom:'6px', textTransform:'uppercase', letterSpacing:'0.05em' } }, 'Words (' + found.length + '/' + words.length + ')'),
      h('div', { style: { display:'flex', flexWrap:'wrap', gap:'4px' } },
        words.map(function(w) {
          var isFound = found.indexOf(w) !== -1;
          return h('span', { key: w, style: { padding:'3px 8px', borderRadius:'4px', fontSize:'11px', fontWeight:'600', background: isFound ? 'var(--ok)' : 'var(--panel)', color: isFound ? '#fff' : 'var(--t2)', textDecoration: isFound ? 'line-through' : 'none', transition:'all 150ms ease' } }, w);
        })
      )
    );
  };

  window.WS.LiveSpyOverlay = function() { return null; };

  window.WS.PuzzleGrid = function(props) {
    var grid = props.grid || [], mask = props.mask || [], selCells = props.selCells || [];
    var foundWords = props.foundWords || [];
    var placements = props.placements || {};
    var hlColor = props.hlColor || '#6366f1';
    var showSol = props.showSol || false;
    var cfg = props.cfg || {};
    var cellSize = props.cellSize || 28;
    var fontWeight = props.fontWeight || '600';

    if (!grid.length) return h('div', { style: { padding:'40px', textAlign:'center', color:'var(--t3)', fontSize:'14px' } }, 'Generate a puzzle to see the grid');

    var solvedCells = {};
    if (showSol) {
      Object.keys(placements).forEach(function(w) {
        var cells = placements[w];
        if (cells) cells.forEach(function(c) { solvedCells[c[0]+','+c[1]] = true; });
      });
    }

    var foundCellSet = {};
    Object.keys(placements).forEach(function(w) {
      if (foundWords.indexOf(w) !== -1) {
        var cells = placements[w];
        if (cells) cells.forEach(function(c) { foundCellSet[c[0]+','+c[1]] = true; });
      }
    });

    var selSet = {};
    selCells.forEach(function(c) { selSet[c[0]+','+c[1]] = true; });

    var rows = grid.length;
    var cols = grid[0] ? grid[0].length : 0;

    return h('div', { style: { display:'inline-block', background: cfg.backgroundColor || '#fff', borderRadius:'8px', padding:'8px', border: '1px solid var(--border)', boxShadow:'var(--shadow-md)' } },
      h('div', { style: { display:'grid', gridTemplateColumns:'repeat('+cols+', '+cellSize+'px)', gap:'1px', background:'var(--border)', borderRadius:'4px', overflow:'hidden' } },
        grid.reduce(function(acc, row, r) {
          row.forEach(function(letter, c) {
            var key = r+','+c;
            var isSel = !!selSet[key];
            var isFound = !!foundCellSet[key];
            var isSolved = !!solvedCells[key];
            var isActive = mask[r] && mask[r][c];
            var bg = isFound ? hlColor : isSel ? hlColor + '33' : isSolved ? hlColor + '22' : (cfg.backgroundColor || '#fff');
            var color = isFound ? '#fff' : (cfg.fontColor || '#1a1a2e');
            var style = {
              width: cellSize + 'px', height: cellSize + 'px',
              display:'flex', alignItems:'center', justifyContent:'center',
              fontSize: Math.round(cellSize * 0.55) + 'px', fontWeight: fontWeight,
              fontFamily: cfg.fontFamily || 'monospace',
              background: isActive ? bg : 'transparent',
              color: isActive ? color : 'transparent',
              transition: 'all 100ms ease',
              userSelect: 'none',
              cursor: 'pointer'
            };
            acc.push(h('div', { key: key, style: style, onMouseDown: function(){ if(props.onMouseDown) props.onMouseDown(r,c); }, onMouseEnter: function(){ if(props.onMouseEnter) props.onMouseEnter(r,c); }, onMouseUp: function(){ if(props.onMouseUp) props.onMouseUp(); } }, letter || '.'));
          });
          return acc;
        }, [])
      )
    );
  };

  function Toggle(props) {
    var checked = props.checked || false;
    var label = props.l || '';
    var sub = props.sub || '';
    var fn = props.fn || function(){};
    return h('div', { style: { display:'flex', alignItems:'center', justifyContent:'space-between', padding:'6px 0', borderBottom:'1px solid var(--border)' } },
      h('div', { style: { flex:1 } },
        h('label', { style: { fontSize:'12px', fontWeight:'600', color:'var(--t1)', cursor:'pointer' } }, label),
        sub ? h('div', { style: { fontSize:'10px', color:'var(--t3)', marginTop:'2px' } }, sub) : null
      ),
      h('div', { onClick: function(){ fn(!checked); }, style: { width:'36px', height:'20px', borderRadius:'10px', background: checked ? 'var(--accent)' : 'var(--border)', position:'relative', cursor:'pointer', transition:'background 150ms ease', flexShrink:'0', marginLeft:'8px' } },
        h('div', { style: { width:'16px', height:'16px', borderRadius:'50%', background:'#fff', position:'absolute', top:'2px', left: checked ? '18px' : '2px', transition:'left 150ms ease', boxShadow:'0 1px 3px rgba(0,0,0,0.2)' } })
      )
    );
  }

  function Select(props) {
    var label = props.l || '';
    var value = props.v || '';
    var opts = props.opts || [];
    var on = props.on || function(){};
    return h('div', { style: { marginBottom:'6px' } },
      h('label', { style: { display:'block', fontSize:'10px', fontWeight:'600', color:'var(--t3)', marginBottom:'3px', textTransform:'uppercase', letterSpacing:'0.05em' } }, label),
      h('select', { value: value, onChange: function(e){ on(e.target.value); }, style: { width:'100%', padding:'6px 8px', border:'1px solid var(--border)', borderRadius:'6px', fontSize:'12px', background:'var(--panel)', color:'var(--t1)', fontFamily:'var(--font)', outline:'none' } },
        opts.map(function(o){ return h('option', { key: o.v, value: o.v }, o.l); })
      )
    );
  }

  function Slider(props) {
    var label = props.l || '';
    var value = props.v || 0;
    var mn = props.mn || 0;
    var mx = props.mx || 100;
    var st = props.st || 1;
    var on = props.on || function(){};
    return h('div', { style: { marginBottom:'6px' } },
      h('div', { style: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'3px' } },
        h('label', { style: { fontSize:'10px', fontWeight:'600', color:'var(--t3)', textTransform:'uppercase', letterSpacing:'0.05em' } }, label),
        h('span', { style: { fontSize:'11px', fontWeight:'700', color:'var(--accent)', fontFamily:'monospace' } }, value)
      ),
      h('input', { type:'range', min:mn, max:mx, step:st, value:value, onChange:function(e){ on(Number(e.target.value)); }, style: { width:'100%', accentColor:'var(--accent)' } })
    );
  }

  function Progress(props) {
    var done = props.done || 0;
    var total = props.total || 1;
    var label = props.label || '';
    var pct = Math.round((done / total) * 100);
    return h('div', { style: { padding:'8px 12px', background:'var(--bg)', borderRadius:'6px', border:'1px solid var(--border)' } },
      h('div', { style: { fontSize:'10px', color:'var(--t3)', marginBottom:'4px' } }, label),
      h('div', { style: { height:'4px', background:'var(--border)', borderRadius:'2px', overflow:'hidden' } },
        h('div', { style: { height:'100%', width: pct+'%', background:'var(--accent)', borderRadius:'2px', transition:'width 200ms ease' } })
      )
    );
  }

  function App(){
    var WS = window.WS || {};
    var PuzzleGrid = WS.PuzzleGrid;
    var WordList = WS.WordList;
    var Toast = WS.Toast;
    var cfgState = useState(Object.assign({}, INIT));
    var cfg = cfgState[0], setCfg = cfgState[1];
    var wordTextState = useState((window.AI_THEMES && window.AI_THEMES.Dragon ? window.AI_THEMES.Dragon : []).join('\n'));
    var wordText = wordTextState[0], setWordText = wordTextState[1];
    var currentThemeState = useState('Dragon');
    var currentTheme = currentThemeState[0], setCurrentTheme = currentThemeState[1];
    var puzzlesState = useState([]);
    var puzzles = puzzlesState[0], setPuzzles = puzzlesState[1];
    var pageState = useState(0);
    var page = pageState[0], setPage = pageState[1];
    var viewState = useState('puzzle');
    var view = viewState[0], setView = viewState[1];
    var foundWordsState = useState([]);
    var foundWords = foundWordsState[0], setFoundWords = foundWordsState[1];
    var selectingState = useState(false);
    var selecting = selectingState[0], setSelecting = selectingState[1];
    var selStartState = useState(null);
    var selStart = selStartState[0], setSelStart = selStartState[1];
    var selCellsState = useState([]);
    var selCells = selCellsState[0], setSelCells = selCellsState[1];
    var toastState = useState(null);
    var toast = toastState[0], setToast = toastState[1];
    var generatingState = useState(false);
    var generating = generatingState[0], setGenerating = generatingState[1];
    var progressState = useState(null);
    var progress = progressState[0], setProgress = progressState[1];
    var statsState = useState(null);
    var stats = statsState[0], setStats = statsState[1];
    var isKingState = useState(localStorage.getItem('mxd_king') === 'true');
    var isKing = isKingState[0], setIsKing = isKingState[1];

    var onlineState = useState(navigator.onLine);
    var isOnline = onlineState[0], setIsOnline = onlineState[1];
    var connDegradedState = useState(false);
    var connDegraded = connDegradedState[0], setConnDegraded = connDegradedState[1];

    useEffect(function(){
      function handleOnline(){ setIsOnline(true); setConnDegraded(false); }
      function handleOffline(){ setIsOnline(false); setConnDegraded(false); }
      window.addEventListener('online', handleOnline);
      window.addEventListener('offline', handleOffline);
      var connHandlers = [];
      if(window.MXDConnectivity){
        try {
          if(window.MXDConnectivity.getStatus){
            var st = window.MXDConnectivity.getStatus();
            setIsOnline(st.online !== false);
            setConnDegraded(st.state === 'degraded');
          }
          var isFileProtocol = window.location.protocol === 'file:';
          window.MXDConnectivity.init({
            heartbeatIntervalMs: isFileProtocol ? 0 : 30000,
            maxHeartbeatFailures: 3
          });
          if(!isFileProtocol){
            var onOnline = function(){ setIsOnline(true); setConnDegraded(false); };
            var onOffline = function(){ setIsOnline(false); setConnDegraded(false); };
            var onDegraded = function(){ setConnDegraded(true); };
            window.MXDConnectivity.on('online', onOnline);
            window.MXDConnectivity.on('offline', onOffline);
            window.MXDConnectivity.on('degraded', onDegraded);
            connHandlers = [onOnline, onOffline, onDegraded];
          }
        } catch(e) { console.warn('[MXD] Connectivity init error:', e); }
      }
      return function(){
        window.removeEventListener('online', handleOnline);
        window.removeEventListener('offline', handleOffline);
        if(window.MXDConnectivity && window.MXDConnectivity.off){
          connHandlers.forEach(function(fn){
            window.MXDConnectivity.off('online', fn);
            window.MXDConnectivity.off('offline', fn);
            window.MXDConnectivity.off('degraded', fn);
          });
        }
      };
    }, []);

    var set = function(key, val) { setCfg(function(p) { var n = Object.assign({}, p); n[key] = val; return n; }); };

    var tabState = useState('settings');
    var tab = tabState[0], setTab = tabState[1];

    var playState = useState(null);
    var playState2 = playState[0], setPlayState = playState[1];
    var timerElapsedState = useState(0);
    var timerElapsed = timerElapsedState[0], setTimerElapsed = timerElapsedState[1];
    var timerRef = useRef(null);

    var showToast = useCallback(function(message,type){
      if(window.showToast) window.showToast(message, type||'info');
      setToast({message:message,type:type||'info'});
      setTimeout(function(){ setToast(null); }, 3000);
    }, []);

    var checkCode = function(code) {
      if(code === 'kingofdragonsismxd') {
        setIsKing(true);
        localStorage.setItem('mxd_king', 'true');
        showToast("KING MODE ACTIVATED: All features unlocked!", "success");
        if(window.MXDInteractive) window.MXDInteractive.unlockAchievement('king_mode');
        return true;
      }
      return false;
    };

    var rawTmpl = (cfg.visualThemeId && window.MXD_VISUAL_THEMES) ?
      window.MXD_VISUAL_THEMES.getTemplate(cfg.visualThemeId) :
      window.TEMPLATES[cfg.template];
    var tmpl = rawTmpl || window.TEMPLATES.classic;

    var normalizedTmpl = {
      bg: tmpl.bg || tmpl.colors && tmpl.colors.bg || '#ffffff',
      tc: tmpl.tc || tmpl.colors && tmpl.colors.text || '#000000',
      cc: tmpl.cc || tmpl.colors && tmpl.colors.accent || '#6366f1',
      ac: tmpl.ac || tmpl.colors && tmpl.colors.accent || '#6366f1',
      ff: tmpl.ff || tmpl.fontFamily || 'sans-serif',
      borderStyle: tmpl.borderStyle || 'none',
      pattern: tmpl.pattern || 'none',
      decorations: tmpl.decorations || []
    };

    useEffect(function() {
      document.body.className = cfg.uiTheme === 'night' ? 'dark' : '';
    }, [cfg.uiTheme]);

    useEffect(function(){
      if(!cfg.showTimer || !playState2 || !window.MXDPlayMode || !window.MXDPlayMode.timer) return;
      var timerInterval = setInterval(function(){
        setTimerElapsed(function(prev){ return prev + 1; });
      }, 1000);
      return function(){ clearInterval(timerInterval); };
    }, [cfg.showTimer, playState2]);

    var generate = useCallback(function(){
      var currentCfg = cfg;
      var currentWordText = wordText;
      var sizeParts = (currentCfg.gridSize || '15x15').split('x');
      var rows = parseInt(sizeParts[0]) || 15;
      var cols = parseInt(sizeParts[1]) || 15;
      var words = parseWords(currentWordText).slice(0, currentCfg.wordsPerGrid);
      if(!words.length) { showToast('Add words to generate a puzzle', 'warn'); return; }

      var engine = window.WordSearchEngine;
      if(!engine || typeof engine.generate !== 'function') {
        console.error('[MXD] WordSearchEngine.generate not loaded. Engine:', typeof engine, engine ? Object.keys(engine).slice(0,5) : 'null');
        showToast('Engine not loaded - check console', 'error');
        return;
      }

      var shape = currentCfg.shape || 'square';
      if(shape === 'dragon') shape = 'square';

      var fullCfg = {
        words: words,
        rows: rows,
        cols: cols,
        allowDiag: currentCfg.allowDiag !== false,
        allowReverse: currentCfg.allowReverse !== false,
        allowH: currentCfg.allowH !== false,
        allowV: currentCfg.allowV !== false,
        overlapPolicy: currentCfg.overlap === 'none' ? 'none' : 'matchOnly',
        placement: currentCfg.placement || 'balanced',
        strategy: currentCfg.placement || 'balanced',
        priority: currentCfg.placeOrder || 'longestFirst',
        fillerMode: currentCfg.fillerMode || 'random',
        letterCase: currentCfg.letterCase || 'upper',
        seed: currentCfg.seed || Date.now(),
        difficulty: currentCfg.difficulty || 'medium',
        shape: shape
      };

      console.log('[MXD Generate] Config:', JSON.stringify(fullCfg));
      console.log('[MXD Generate] Calling engine with', words.length, 'words,', rows + 'x' + cols);
      setGenerating(true);

      try {
        var result = engine.generate(fullCfg);
        console.log('[MXD Generate] Result type:', typeof result, result ? 'grid=' + (result.grid ? result.grid.length : 'none') + ', placements=' + Object.keys(result.placements || {}).length : 'null');

        if(!result || !result.grid || !result.grid.length) {
          showToast('Could not place words - try fewer words or larger grid', 'warn');
          setGenerating(false);
          return;
        }

        var puzzle = { grid: result.grid, mask: result.mask || [], placements: result.placements || {} };
        console.log('[MXD Generate] Puzzle set:', puzzle.grid.length, 'rows,', Object.keys(puzzle.placements).length, 'words placed');

        setPuzzles([puzzle]);
        setPage(0);
        setFoundWords([]);
        setSelCells([]);
        setView('puzzle');
        if(window.MXDPlayMode && window.MXDPlayMode.createGameState){
          try {
            var placedWords = Object.keys(puzzle.placements);
            var playPuzzle = {
              grid: puzzle.grid,
              mask: puzzle.mask,
              placements: placedWords.map(function(w){ return puzzle.placements[w]; }),
              words: placedWords
            };
            var gs = window.MXDPlayMode.createGameState(playPuzzle, {mode: currentCfg.playMode || 'practice', maxHints: currentCfg.maxHints || 3});
            setPlayState(gs);
          } catch(e) { console.warn('[MXD] Play state error:', e); setPlayState(null); }
        }
        setTimerElapsed(0);
        setGenerating(false);
        var placedCount = Object.keys(puzzle.placements).length;
        showToast('Puzzle generated! ' + placedCount + '/' + words.length + ' words placed', 'success');

        if(window.MXDOffline && window.MXDOffline.saveConfig) {
          try { window.MXDOffline.saveConfig(currentCfg); } catch(e) {}
        }
      } catch(e) {
        console.error('[MXD Generate] Error:', e);
        setGenerating(false);
        showToast('Generation error: ' + e.message, 'error');
      }
    }, [wordText, cfg]);

    useEffect(function(){
      if(window.MXDOffline && window.MXDOffline.loadConfig){
        window.MXDOffline.loadConfig().then(function(savedCfg){
          if(savedCfg && savedCfg.data) {
            setCfg(function(prev){ return Object.assign({}, prev, savedCfg.data); });
          }
        }).catch(function(){});
      }
    }, []);

    useEffect(function(){
      return function(){ if(timerRef.current) clearInterval(timerRef.current); };
    }, []);

    var handleBulkExport = useCallback(function(){
      setGenerating(true);
      var generated = [];
      var targetCount = cfg.bulkPageCount || 100;
      showToast("Building book with " + targetCount + " pages...", "info");

      var engine = window.WordSearchEngine || {generate:function(){return {grid:[],mask:[],placements:{}};}};
      var words = parseWords(wordText);

      setTimeout(function() {
        for(var i = 0; i < targetCount; i++){
          var result = engine.generate({words:words, rows:parseInt(cfg.gridSize)||15, cols:parseInt(cfg.gridSize)||15, allowDiag:cfg.allowDiag, allowReverse:cfg.allowReverse});
          generated.push(result);
          setProgress({done:i+1, total:targetCount, label:"Generating page " + (i+1) + "/" + targetCount});
        }
        setPuzzles(generated);

        if(window.MXDExportBookBuilder && window.jspdf && window.jspdf.jsPDF){
          var bb = window.MXDExportBookBuilder;
          var marginPresets = bb.MARGIN_PRESETS || {};
          var trimSizes = bb.TRIM_SIZES || {};
          var marginKey = cfg.marginPreset || 'standard';
          var margins = marginPresets[marginKey] || marginPresets.standard || {top:36,bottom:36,left:36,right:36};
          var trimKey = cfg.pageSize || '8.5x11';
          var trimSize = trimSizes[trimKey] || trimSizes['8.5x11'] || {width:612,height:792};

          var bookConfig = {
            trimSize: trimKey,
            margins: margins,
            bleed: cfg.bleed > 0,
            title: cfg.title || 'Word Search Book',
            includeCover: cfg.includeCover,
            includeTOC: cfg.includeTOC,
            showSolutions: cfg.showSolution,
            fontFamily: cfg.fontFamily || 'Arial',
            fontSize: cfg.gridFontSize || 16,
            cellSize: cfg.cellSize || 24
          };

          try {
            var pages = bb.bookBuilder ? bb.bookBuilder.build(generated, bookConfig) : [];
            var pdf = new window.jspdf.jsPDF({ orientation:'portrait', unit:'pt', format:[trimSize.width, trimSize.height] });
            for(var p=0; p<pages.length; p++){
              if(p > 0) pdf.addPage([trimSize.width, trimSize.height], 'portrait');
              if(pages[p] && pages[p].canvas) {
                var imgData = pages[p].canvas.toDataURL('image/png');
                pdf.addImage(imgData, 'PNG', 0, 0, trimSize.width, trimSize.height);
              }
            }
            var fileName = (cfg.exportName || cfg.title || 'word-search').replace(/\s+/g, '-') + '.pdf';
            pdf.save(fileName);
            showToast("SUCCESS: " + generated.length + "-page book exported!", 'success');
          } catch(e) {
            showToast('Export error: ' + e.message + '. Try Print instead.', 'error');
          }
        } else if(window.PdfExport && window.PdfExport.generate) {
          window.PdfExport.generate(generated, {title:cfg.title}, function(done,total,label){setProgress({done:done,total:total,label:label});});
          showToast("SUCCESS: Full " + generated.length + "-Page Book Created", 'success');
        } else {
          window.print();
          showToast("Opened print dialog for export", 'info');
        }
        setGenerating(false); setProgress(null);
      }, 300);
    }, [wordText, cfg]);

    var onMouseDown = function(r,c) { setSelecting(true); setSelStart([r,c]); setSelCells([[r,c]]); };
    var onMouseEnter = function(r,c) { if(!selecting || !selStart) return; var cells = getCellsBetween(selStart[0], selStart[1], r, c); if(cells.length) setSelCells(cells); };
    var onMouseUp = function() {
      if(!selecting || !puzzles.length) { setSelecting(false); return; }
      setSelecting(false);
      var pz = puzzles[page];
      if(!pz || !pz.grid) { setSelCells([]); return; }
      var selStr = selCells.map(function(c) { return (pz.grid[c[0]] && pz.grid[c[0]][c[1]]) || ''; }).join('');
      var selRev = selStr.split('').reverse().join('');
      var placedWords = Object.keys(pz.placements || {});
      for(var i = 0; i < placedWords.length; i++) {
        var w = placedWords[i];
        var ww = cfg.letterCase === 'lower' ? w.toLowerCase() : w.toUpperCase();
        if((selStr === ww || selRev === ww) && foundWords.indexOf(w) === -1) {
          setFoundWords(function(p) { return p.concat([w]); });
          showToast("FOUND: \"" + w + "\"", 'success');
          if(window.MXDInteractive) window.MXDInteractive.incrementAchievement('word_finder');
          if(playState2 && window.MXDPlayMode){
            var newState = Object.assign({}, playState2, {
              foundWords: foundWords.concat([w]),
              score: window.MXDPlayMode.scoring ? window.MXDPlayMode.scoring.calculate(timerElapsed * 1000, cfg.difficulty || 'medium', playState2.hintsUsed || 0, foundWords.length + 1, placedWords.length) : 0
            });
            setPlayState(newState);
            if(foundWords.length + 1 === placedWords.length){
              newState.completed = true;
              newState.completedAt = Date.now();
              setTimerElapsed(0);
              showToast("PUZZLE COMPLETE! Score: " + newState.score, 'success');
            }
          }
          break;
        }
      }
      setSelCells([]);
    };

    var useHint = function(){
      if(!playState2 || !puzzles.length) return;
      if(playState2.hintsRemaining <= 0){ showToast('No hints remaining!', 'warn'); return; }
      if(!window.MXDPlayMode || !window.MXDPlayMode.hints) return;
      var hint = window.MXDPlayMode.hints.revealFirstLetter(playState2);
      if(hint){
        setPlayState(Object.assign({}, playState2, { hintsUsed: (playState2.hintsUsed||0) + 1, hintsRemaining: (playState2.hintsRemaining||0) - 1 }));
        showToast('Hint: "' + hint.word + '" starts at row ' + (hint.cell.row+1) + ', col ' + (hint.cell.col+1), 'info');
        setSelCells([[hint.cell.row, hint.cell.col]]);
        setTimeout(function(){ setSelCells([]); }, 1500);
      }
    };

    if (!PuzzleGrid) return h('div', {style:{padding:50, color:'#333', textAlign:'center', fontFamily:'sans-serif'}}, h('h2', null, 'Loading MXD...'), h('p', {style:{color:'#666'}}, 'Preparing puzzle engine...'));

    var wordBankNames = (window.WORD_BANKS || []).map(function(b){ return b.n; });
    var themeNames = Object.keys(window.AI_THEMES || {});

    var quickSettings = h('div', {className:'sec', key:'quick'},
      h('div', {className:'sec-hd'},
        h('span', {className:'sec-ttl'}, h('span', {className:'sec-ico'}), 'Quick Settings'),
        h('span', {className:'sec-ch'}, '\u25bc')
      ),
      h('div', {className:'sec-bd'},
        h('div', {style:{marginBottom:6}},
          h('span', {className:'lbl'}, 'Words (one per line or comma-separated)'),
          h('textarea', {className:'wta', value:wordText, onChange:function(e){setWordText(e.target.value);}, rows:4})
        ),
        h('div', {className:'chips', style:{marginBottom:8}},
          (window.AI_THEMES ? Object.keys(window.AI_THEMES).slice(0,8) : []).map(function(k){
            return h('span', {key:k, className:'chip'+(currentTheme===k?' on':''), onClick:function(){setCurrentTheme(k); setWordText(window.AI_THEMES[k].join('\n'));}}, k);
          })
        ),
        h('button', {className:'btn btn-pri btn-full', onClick:generate, disabled:generating}, generating?'Generating...':'Generate Puzzle'),
        h('div', {className:'row', style:{marginTop:8}},
          h(Select, {l:'Grid', v:cfg.gridSize||'15x15', opts:[{v:'10x10',l:'10x10'},{v:'15x15',l:'15x15'},{v:'20x20',l:'20x20'},{v:'25x25',l:'25x25'}], on:function(v){set('gridSize',v);}}),
          h(Select, {l:'Difficulty', v:cfg.difficulty||'medium', opts:[{v:'easy',l:'Easy'},{v:'medium',l:'Medium'},{v:'hard',l:'Hard'},{v:'expert',l:'Expert'}], on:function(v){set('difficulty',v);}})
        ),
        h(Slider, {l:'Words', v:cfg.wordsPerGrid||15, mn:5, mx:40, on:function(v){set('wordsPerGrid',v);}}),
        h(Slider, {l:'Cell Size', v:cfg.cellSize||28, mn:16, mx:48, on:function(v){set('cellSize',v);}})
      )
    );

    var advancedSettings = h('div', {className:'sec', key:'advanced'},
      h('div', {className:'sec-hd'},
        h('span', {className:'sec-ttl'}, h('span', {className:'sec-ico'}), 'Advanced'),
        h('span', {className:'sec-ch'}, '\u25bc')
      ),
      h('div', {className:'sec-bd'},
        h(Toggle, {l:'Diagonal', checked:!!cfg.allowDiag, fn:function(v){set('allowDiag',v);}}),
        h(Toggle, {l:'Reverse', checked:!!cfg.allowReverse, fn:function(v){set('allowReverse',v);}}),
        h(Select, {l:'Placement', v:cfg.placement||'balanced', opts:[{v:'compact',l:'Compact'},{v:'balanced',l:'Balanced'},{v:'spread',l:'Spread'}], on:function(v){set('placement',v);}}),
        h(Select, {l:'Overlap', v:cfg.overlap||'match', opts:[{v:'none',l:'None'},{v:'match',l:'Match Letters'},{v:'cross',l:'Allow Crossings'}], on:function(v){set('overlap',v);}}),
        h(Select, {l:'Cell Shape', v:cfg.cellShape||'square', opts:[{v:'square',l:'Square'},{v:'circle',l:'Circle'},{v:'rounded',l:'Rounded'}], on:function(v){set('cellShape',v);}}),
        h(Select, {l:'UI Theme', v:cfg.uiTheme||'day', opts:[{v:'day',l:'Day'},{v:'night',l:'Night'},{v:'cyber',l:'Cyber'}], on:function(v){set('uiTheme',v);}}),
        h('div', {className:'div'}),
        h('button', {className:'btn btn-sec btn-full', onClick:function(){
          if(window.MXDWordListTools){
            var tools = window.MXDWordListTools;
            var words = parseWords(wordText);
            var shuffled = tools.shuffle ? tools.shuffle(words) : words;
            setWordText(shuffled.join('\n'));
            showToast('Words shuffled!', 'info');
          }
        }}, 'Shuffle Words'),
        h('button', {className:'btn btn-sec btn-full', style:{marginTop:4}, onClick:function(){
          if(window.MXDWordListTools){
            var words = parseWords(wordText);
            var noDupes = window.MXDWordListTools.removeDuplicates ? window.MXDWordListTools.removeDuplicates(words) : words.filter(function(w,i,a){return a.indexOf(w)===i;});
            setWordText(noDupes.join('\n'));
            showToast('Duplicates removed (' + (words.length - noDupes.length) + ')', 'info');
          }
        }}, 'Remove Duplicates')
      )
    );

    var presetsContent = h('div', {key:'presets'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}, 'Saved Presets'), h('span', {className:'sec-ch'}, '\u25bc')),
        h('div', {className:'sec-bd'},
          h('button', {className:'btn btn-pri btn-full', onClick:function(){
            if(window.MXDPresets && window.MXDPresets.save){
              var name = prompt('Preset name:');
              if(name){ window.MXDPresets.save(name, cfg); showToast('Preset saved: ' + name, 'success'); }
            } else { showToast('Preset system not loaded', 'warn'); }
          }}, 'Save Current as Preset'),
          h('button', {className:'btn btn-sec btn-full', style:{marginTop:4}, onClick:function(){
            if(window.MXDPresets && window.MXDPresets.getAll){
              var all = window.MXDPresets.getAll();
              var names = Object.keys(all || {});
              if(!names.length){ showToast('No presets saved', 'info'); return; }
              var name = prompt('Load preset:\n' + names.join('\n'));
              if(name && all[name]){
                setCfg(Object.assign({}, cfg, all[name]));
                showToast('Preset loaded: ' + name, 'success');
              }
            }
          }}, 'Load Preset')
        )
      )
    );

    var kdpContent = h('div', {key:'kdp'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Trademark Checker'),
        h('div', {className:'sec-bd'},
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Title to check'),
            h('input', {className:'txt-in', value:cfg.title, onChange:function(e){set('title',e.target.value);}})
          ),
          h('button', {className:'btn btn-pri btn-full', onClick:function(){
            var title = cfg.title.toLowerCase();
            var tmList = (window.MXDKDPSuite && window.MXDKDPSuite.data && window.MXDKDPSuite.data.trademarks) || ['disney','amazon','lego','marvel','star wars','harry potter','nintendo','pokemon','dc comics','warner bros','pixar','dreamworks','barbie','transformers'];
            var found = tmList.filter(function(b){ return title.indexOf(b.toLowerCase()) !== -1; });
            if(found.length) showToast("TRADEMARK ALERT: \"" + found.join('", "') + "\" may be protected terms.", "error");
            else showToast("Title appears safe for common trademarks. Always verify officially.", "success");
          }}, 'Check Trademarks')
        )
      ),
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Listing Optimizer'),
        h('div', {className:'sec-bd'},
          h('div', {style:{fontSize:'11px',color:'var(--t2)',marginBottom:8}}, 'Character counts for KDP listing fields'),
          h('div', {className:'stat-r'}, h('span', null, 'Title'), h('span', {className:'stat-v'}, cfg.title.length + '/200')),
          h('div', {className:'stat-r'}, h('span', null, 'Subtitle'), h('span', {className:'stat-v'}, (cfg.subtitle||'').length + '/200')),
          h('div', {style:{marginTop:8}},
            h('span', {className:'lbl'}, 'Subtitle'),
            h('input', {className:'txt-in', value:cfg.subtitle||'', placeholder:'Optional subtitle', onChange:function(e){set('subtitle',e.target.value);}})
          ),
          h('button', {className:'btn btn-sec btn-full', style:{marginTop:8}, onClick:function(){
            var tips = [];
            if(cfg.title.length < 10) tips.push('Title is short - add descriptive keywords');
            if(cfg.title.length > 150) tips.push('Title is very long - may be truncated');
            if(!cfg.subtitle) tips.push('Add a subtitle with target keywords');
            var words = parseWords(wordText);
            if(words.length < 10) tips.push('Add more words for a fuller puzzle book');
            if(tips.length) showToast(tips.join('. '), 'warn');
            else showToast('Listing looks good! Title is descriptive and well-sized.', 'success');
          }}, 'Analyze Listing')
        )
      ),
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Niche Keywords'),
        h('div', {className:'sec-bd'},
          h('div', {style:{fontSize:'11px',color:'var(--t2)',marginBottom:8}}, 'Popular word search niche keywords'),
          (window.CATEGORY_DB || []).map(function(cat){
            return h('div', {key:cat.id, className:'cat-item'},
              h('div', {className:'cat-name'}, cat.n),
              h('div', {className:'cat-path'}, cat.path)
            );
          })
        )
      ),
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'BSR & Royalty Calculator'),
        h('div', {className:'sec-bd'},
          h('div', {className:'row'},
            h('div', {style:{flex:1}}, h('span', {className:'lbl'}, 'Price ($)'), h('input', {className:'num-in', type:'number', id:'kdp-price', defaultValue:'9.99'})),
            h('div', {style:{flex:1}}, h('span', {className:'lbl'}, 'Pages'), h('input', {className:'num-in', type:'number', id:'kdp-pages', defaultValue:'100'}))
          ),
          h('button', {className:'btn btn-sec btn-full', style:{marginTop:8}, onClick:function(){
            var price = parseFloat(document.getElementById('kdp-price').value) || 9.99;
            var pages = parseInt(document.getElementById('kdp-pages').value) || 100;
            if(window.MXDKDPSuite && window.MXDKDPSuite.utils && window.MXDKDPSuite.utils.calcRoyalty){
              var result = window.MXDKDPSuite.utils.calcRoyalty(price, pages);
              showToast('Printing: $' + result.printCost.toFixed(2) + ' | Royalty: $' + result.royalty.toFixed(2) + ' | Margin: ' + result.margin + '%', 'info');
            } else {
              var printingCost = 0.012 * pages;
              var royalty = (price * 0.6) - printingCost;
              showToast('Printing: $' + printingCost.toFixed(2) + ' | Royalty: $' + Math.max(0, royalty).toFixed(2) + ' per sale', 'info');
            }
          }}, 'Calculate Royalty')
        )
      )
    );

    var bulkContent = h('div', {key:'bulk'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Bulk Book Builder'),
        h('div', {className:'sec-bd'},
          h(Toggle, {l:'Bulk Mode', checked:cfg.bulkMode, fn:function(v){set('bulkMode',v);}, sub:cfg.bulkMode?'Generates '+cfg.bulkPageCount+' puzzles':''}),
          cfg.bulkMode ? h('div', null,
            h(Slider, {l:'Pages', v:cfg.bulkPageCount, mn:1, mx:500, on:function(v){set('bulkPageCount',v);}}),
            h('div', {className:'div'}),
            h(Toggle, {l:'Table of Contents', checked:cfg.includeTOC, fn:function(v){set('includeTOC',v);}}),
            h(Toggle, {l:'Cover Page', checked:cfg.includeCover, fn:function(v){set('includeCover',v);}}),
            h(Toggle, {l:'Show Solutions', checked:cfg.showSolution, fn:function(v){set('showSolution',v);}}),
            h('div', {className:'div'}),
            h(Select, {l:'Page Size', v:cfg.pageSize||'8.5x11', opts:[{v:'8.5x11',l:'8.5 x 11 (Letter)'},{v:'6x9',l:'6 x 9 (Trade)'},{v:'8x10',l:'8 x 10'},{v:'8.5x8.5',l:'8.5 x 8.5 (Square)'},{v:'5x8',l:'5 x 8 (Pocket)'}], on:function(v){set('pageSize',v);}}),
            h(Select, {l:'Margins', v:cfg.marginPreset||'standard', opts:[{v:'standard',l:'Standard'},{v:'narrow',l:'Narrow'},{v:'wide',l:'Wide'},{v:'custom',l:'Custom'}], on:function(v){set('marginPreset',v);}}),
            h(Toggle, {l:'Bleed (0.125in)', checked:!!cfg.bleed, fn:function(v){set('bleed',v?9:0);}}),
            h('div', {className:'div'}),
            h('div', {className:'kdp-card'},
              h('h4', null, 'Book Summary'),
              h('div', {className:'kdp-stat'}, h('span', null, 'Trim'), h('span', {className:'kdp-v'}, cfg.pageSize)),
              h('div', {className:'kdp-stat'}, h('span', null, 'Puzzles'), h('span', {className:'kdp-v'}, ''+cfg.bulkPageCount)),
              h('div', {className:'kdp-stat'}, h('span', null, 'Words/Grid'), h('span', {className:'kdp-v'}, ''+cfg.wordsPerGrid)),
              h('div', {className:'kdp-stat'}, h('span', null, 'Total Pages'), h('span', {className:'kdp-v'}, ''+(cfg.bulkPageCount+(cfg.showSolution?cfg.bulkPageCount:0)+(cfg.includeCover?1:0)+(cfg.includeTOC?1:0))))
            ),
            h('button', {className:'btn btn-ok btn-full', style:{marginTop:8}, onClick:handleBulkExport, disabled:generating}, generating?'Generating...':'Generate Book PDF')
          ) : h('div', {className:'info', style:{marginTop:8}}, 'Turn on Bulk Mode to configure multi-puzzle book exports')
        )
      )
    );

    var exportContent = h('div', {key:'export'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Export'),
        h('div', {className:'sec-bd'},
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Book Title'),
            h('input', {className:'txt-in', value:cfg.title, onChange:function(e){set('title',e.target.value);}})
          ),
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Filename'),
            h('input', {className:'txt-in', value:cfg.exportName||'', placeholder:cfg.title, onChange:function(e){set('exportName',e.target.value);}})
          ),
          h('div', {className:'div'}),
          h(Select, {l:'Format', v:cfg.imageFormat||'png', opts:[{v:'png',l:'PNG (Lossless)'},{v:'jpeg',l:'JPEG (Smaller)'}], on:function(v){set('imageFormat',v);}}),
          h(Slider, {l:'DPI', v:cfg.dpi||300, mn:300, mx:600, st:100, on:function(v){set('dpi',v);}}),
          h('div', {className:'div'}),
          h('div', {style:{display:'flex',gap:4,flexWrap:'wrap'}},
            h('button', {className:'btn btn-ok', style:{flex:1}, onClick:handleBulkExport, disabled:generating}, generating?'...':'PDF Book'),
            (puzzles && puzzles.length > 0) ? h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){
              var pz = puzzles[0];
              if(!pz || !pz.grid) { showToast('Generate a puzzle first', 'warn'); return; }
              var canvas = document.createElement('canvas');
              var scale = (cfg.dpi || 300) / 96;
              var cellPx = Math.round((cfg.cellSize || 28) * scale);
              var cols = pz.grid[0] ? pz.grid[0].length : 0;
              var rows = pz.grid.length;
              canvas.width = cols * cellPx + 80;
              canvas.height = rows * cellPx + 120;
              var ctx = canvas.getContext('2d');
              ctx.fillStyle = '#ffffff';
              ctx.fillRect(0, 0, canvas.width, canvas.height);
              ctx.fillStyle = '#1a1a2e';
              ctx.font = 'bold ' + Math.round(18*scale) + 'px Inter, sans-serif';
              ctx.textAlign = 'center';
              ctx.fillText(cfg.title || 'Word Search', canvas.width/2, 30*scale);
              ctx.font = Math.round(cellPx*0.55) + 'px monospace';
              ctx.textAlign = 'center';
              ctx.textBaseline = 'middle';
              for(var r=0;r<rows;r++){
                for(var c=0;c<cols;c++){
                  var letter = (pz.grid[r] && pz.grid[r][c]) || '.';
                  var isActive = pz.mask && pz.mask[r] && pz.mask[r][c];
                  ctx.fillStyle = isActive ? '#1a1a2e' : '#e5e7eb';
                  ctx.fillRect(40+c*cellPx, 50+r*cellPx, cellPx-1, cellPx-1);
                  if(isActive){
                    ctx.fillStyle = '#1a1a2e';
                    ctx.fillText(letter, 40+c*cellPx+cellPx/2, 50+r*cellPx+cellPx/2);
                  }
                }
              }
              var fmt = cfg.imageFormat === 'jpeg' ? 'image/jpeg' : 'image/png';
              var ext = cfg.imageFormat === 'jpeg' ? 'jpg' : 'png';
              var a = document.createElement('a');
              a.href = canvas.toDataURL(fmt, cfg.jpegQuality || 0.95);
              a.download = (cfg.exportName || cfg.title || 'puzzle').replace(/\s+/g, '-') + '.' + ext;
              a.click();
              showToast('Puzzle exported as ' + ext.toUpperCase(), 'success');
            }}, 'PNG') : null,
            (puzzles && puzzles.length > 0) ? h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){
              if(window.MXDAnswerKey && puzzles.length){
                try {
                  var doc = window.MXDAnswerKey.generateSolutionsBook(puzzles, {title:cfg.title+' - Solutions'});
                  doc.save(cfg.title.replace(/\s+/g,'-')+'-Solutions.pdf');
                  showToast('Solutions book exported!', 'success');
                } catch(e) { showToast('Answer key export error: ' + e.message, 'error'); }
              } else { showToast('Generate puzzles first', 'warn'); }
            }}, 'Answer Key') : null,
            h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){ window.print(); }}, 'Print')
          )
        )
      )
    );

    var playContent = h('div', {key:'play'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Play Mode'),
        h('div', {className:'sec-bd'},
          h(Select, {l:'Mode', v:cfg.playMode||'practice', opts:[{v:'practice',l:'Practice'},{v:'timed',l:'Timed'},{v:'challenge',l:'Challenge'}], on:function(v){set('playMode',v);}}),
          h(Toggle, {l:'Show Timer', checked:!!cfg.showTimer, fn:function(v){set('showTimer',v);}}),
          h(Toggle, {l:'Show Hints', checked:!!cfg.showHints, fn:function(v){set('showHints',v);}}),
          cfg.showHints ? h(Slider, {l:'Max Hints', v:cfg.maxHints||3, mn:1, mx:10, on:function(v){set('maxHints',v);}}) : null,
          h('div', {className:'div'}),
          playState2 ? h('div', null,
            h('div', {className:'stat-r'}, h('span', null, 'Score'), h('span', {className:'stat-v'}, ''+(playState2.score||0))),
            h('div', {className:'stat-r'}, h('span', null, 'Found'), h('span', {className:'stat-v'}, foundWords.length + '/' + (puzzles[page] ? Object.keys(puzzles[page].placements||{}).length : 0))),
            h('div', {className:'stat-r'}, h('span', null, 'Hints Left'), h('span', {className:'stat-v'}, ''+(playState2.hintsRemaining||0))),
            cfg.showTimer ? h('div', {className:'stat-r'}, h('span', null, 'Time'), h('span', {className:'stat-v'}, Math.floor(timerElapsed/60) + ':' + String(timerElapsed%60).padStart(2,'0'))) : null,
            playState2.completed ? h('div', {style:{textAlign:'center',padding:'12px',background:'var(--ok)',color:'#fff',borderRadius:'8px',marginTop:'8px',fontWeight:'700'}}, 'PUZZLE COMPLETE!') : null,
            h('button', {className:'btn btn-sec btn-full', style:{marginTop:8}, onClick:useHint, disabled:!cfg.showHints||(playState2.hintsRemaining||0)<=0}, 'Use Hint')
          ) : h('div', {className:'info'}, 'Generate a puzzle to start playing')
        )
      ),
      puzzles.length > 0 ? h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Puzzle Navigation'),
        h('div', {className:'sec-bd'},
          h('div', {style:{fontSize:'11px',fontWeight:'600',color:'var(--t2)',marginBottom:'8px'}}, 'Puzzle ' + (page+1) + ' of ' + puzzles.length),
          h('div', {style:{display:'flex',gap:'4px',marginBottom:'12px'}},
            page > 0 ? h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){setPage(page-1);}}, 'Prev') : null,
            h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){setView(view==='solution'?'puzzle':'solution');}}, view==='solution'?'Puzzle':'Solution'),
            page < puzzles.length-1 ? h('button', {className:'btn btn-sec', style:{flex:1}, onClick:function(){setPage(page+1);}}, 'Next') : null
          ),
          h(WordList, {words:puzzles[page] ? Object.keys(puzzles[page].placements||{}) : [], found:foundWords})
        )
      ) : null
    );

    var svgContent = h('div', {key:'svg'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'SVG Shape Studio'),
        h('div', {className:'sec-bd'},
          h('div', {className:'info'}, 'Create and manage custom shapes for puzzle masks'),
          h('div', {style:{display:'flex',gap:4,flexWrap:'wrap'}},
            h('button', {className:'btn btn-pri', onClick:function(){
              if(window.MXDSVGStudio && window.MXDSVGStudio._refreshGrid){
                window.MXDSVGStudio._refreshGrid();
                showToast('SVG Studio refreshed', 'success');
              } else { showToast('SVG Studio not loaded', 'warn'); }
            }}, 'Open Studio'),
            h('button', {className:'btn btn-sec', onClick:function(){
              if(window.MXDMaskPipeline && window.MXDMaskPipeline.SHAPE_PATHS){
                var shapes = Object.keys(window.MXDMaskPipeline.SHAPE_PATHS);
                showToast(shapes.length + ' shapes available: ' + shapes.slice(0,10).join(', ') + (shapes.length>10?'...':''), 'info');
              } else { showToast('Shape pipeline not loaded', 'warn'); }
            }}, 'List Shapes')
          )
        )
      )
    );

    var coverContent = h('div', {key:'cover'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Cover Designer'),
        h('div', {className:'sec-bd'},
          h('div', {className:'info'}, 'Design KDP-compliant book covers with trim, bleed, and spine calculations'),
          h(Select, {l:'Trim Size', v:cfg.pageSize||'8.5x11', opts:[{v:'8.5x11',l:'8.5 x 11'},{v:'6x9',l:'6 x 9'},{v:'8x10',l:'8 x 10'},{v:'5x8',l:'5 x 8'}], on:function(v){set('pageSize',v);}}),
          h('div', {className:'row', style:{marginTop:8}},
            h('div', {style:{flex:1}}, h('span', {className:'lbl'}, 'Page Count'), h('input', {className:'num-in', type:'number', id:'cover-pages', defaultValue:'100'})),
            h('div', {style:{flex:1}}, h('span', {className:'lbl'}, 'Paper'), h('select', {className:'sel', id:'cover-paper'}, h('option',{value:'white'},'White'), h('option',{value:'cream'},'Cream')))
          ),
          h('div', {style:{display:'flex',gap:4,marginTop:8,flexWrap:'wrap'}},
            h('button', {className:'btn btn-pri', onClick:function(){
              if(window.MXDDesigner){
                var pages = parseInt(document.getElementById('cover-pages').value) || 100;
                var paper = document.getElementById('cover-paper').value || 'white';
                var designer = new window.MXDDesigner({trimSize:cfg.pageSize, pageCount:pages, paperType:paper});
                window.MXDDesignerInstance = designer;
                if(window.buildDesignerToolbar){
                  var toolbar = document.createElement('div');
                  toolbar.id = 'mxd-cover-toolbar';
                  toolbar.style.cssText = 'position:fixed;right:0;top:60px;width:280px;height:calc(100vh - 60px);background:#0f172a;overflow-y:auto;z-index:999;padding:12px;';
                  document.body.appendChild(toolbar);
                  window.buildDesignerToolbar(toolbar);
                  showToast('Cover Designer opened', 'success');
                }
              } else { showToast('Cover Designer not loaded', 'warn'); }
            }}, 'Open Designer'),
            h('button', {className:'btn btn-sec', onClick:function(){
              var tb = document.getElementById('mxd-cover-toolbar');
              if(tb) { tb.remove(); showToast('Cover Designer closed', 'info'); }
            }}, 'Close')
          )
        )
      )
    );

    var settingsContent = h('div', {key:'settings'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Settings Profiles'),
        h('div', {className:'sec-bd'},
          h('button', {className:'btn btn-sec btn-full', onClick:function(){
            if(window.MXD_SETTINGS_UI && window.MXD_SETTINGS_UI.show){
              window.MXD_SETTINGS_UI.show();
            } else { showToast('Settings UI not loaded', 'warn'); }
          }}, 'Open Full Settings'),
          h('button', {className:'btn btn-sec btn-full', style:{marginTop:4}, onClick:function(){
            if(window.MXD_SETTINGS && window.MXD_SETTINGS.exportSettings){
              var data = window.MXD_SETTINGS.exportSettings();
              var blob = new Blob([JSON.stringify(data,null,2)], {type:'application/json'});
              var a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'mxd-settings.json'; a.click();
              showToast('Settings exported', 'success');
            }
          }}, 'Export Settings'),
          h('button', {className:'btn btn-sec btn-full', style:{marginTop:4}, onClick:function(){
            var input = document.createElement('input'); input.type='file'; input.accept='.json';
            input.onchange = function(e){
              var file = e.target.files[0];
              if(!file) return;
              var reader = new FileReader();
              reader.onload = function(ev){
                try {
                  var data = JSON.parse(ev.target.result);
                  if(window.MXD_SETTINGS && window.MXD_SETTINGS.importSettings){
                    window.MXD_SETTINGS.importSettings(data);
                    showToast('Settings imported', 'success');
                  }
                } catch(err) { showToast('Invalid settings file', 'error'); }
              };
              reader.readAsText(file);
            };
            input.click();
          }}, 'Import Settings')
        )
      )
    );

    var NAV_ITEMS = [
      {id:'settings', icon:'\u2699\uFE0F', label:'Settings'},
      {id:'niche', icon:'\uD83D\uDD0D', label:'Niche'},
      {id:'kdp', icon:'\uD83D\uDCCA', label:'KDP'},
      {id:'bulk', icon:'\uD83D\uDCDA', label:'Bulk'},
      {id:'export', icon:'\uD83D\uDCE4', label:'Export'},
      {id:'play', icon:'\uD83C\uDFAE', label:'Play'},
      {id:'presets', icon:'\uD83D\uDCBE', label:'Presets'},
      {id:'svg', icon:'\uD83C\uDFA8', label:'SVG'},
      {id:'cover', icon:'\uD83D\uDDBC\uFE0F', label:'Cover'},
      {id:'listopt', icon:'\uD83D\uDCCB', label:'Listing'}
    ];

    var iconBar = h('div', {className:'icon-nav-bar', style:{display:'flex',flexDirection:'row',flexWrap:'wrap',gap:'2px',padding:'6px',borderBottom:'1px solid var(--border)'}},
      NAV_ITEMS.map(function(item){
        return h('button', {key:item.id, className:'icon-nav-btn'+(tab===item.id?' active':''), onClick:function(){setTab(item.id);}, title:item.label, style:{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'6px 4px',border:'none',background:tab===item.id?'var(--accent-light)':'transparent',color:tab===item.id?'var(--accent)':'var(--t3)',borderRadius:'6px',cursor:'pointer',fontSize:'16px',transition:'all 150ms ease',flex:'1 0 auto',minWidth:'52px'}},
          h('span', {style:{fontSize:'16px'}}, item.icon),
          h('span', {style:{fontSize:'8px',fontWeight:'600',marginTop:'1px',whiteSpace:'nowrap'}}, item.label)
        );
      })
    );

    var listOptContent = h('div', {key:'listopt'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Listing Builder'),
        h('div', {className:'sec-bd'},
          h('div', {style:{fontSize:'11px',color:'var(--t2)',marginBottom:8}}, 'Build your KDP listing with character-count guards'),
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Title (' + cfg.title.length + '/200)'),
            h('input', {className:'txt-in', value:cfg.title, maxLength:200, onChange:function(e){set('title',e.target.value);}})
          ),
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Subtitle (' + (cfg.subtitle||'').length + '/200)'),
            h('input', {className:'txt-in', value:cfg.subtitle||'', maxLength:200, placeholder:'e.g. Large Print Word Search for Adults', onChange:function(e){set('subtitle',e.target.value);}})
          ),
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, 'Description (paste your description below)'),
            h('textarea', {className:'wta', id:'kdp-desc', rows:4, placeholder:'Paste or write your book description...'})
          ),
          h('div', {style:{marginBottom:6}},
            h('span', {className:'lbl'}, '7 Backend Keywords (comma-separated)'),
            h('textarea', {className:'wta', id:'kdp-keywords', rows:2, placeholder:'word search, puzzle book, brain teaser, ...'})
          ),
          h('button', {className:'btn btn-pri btn-full', onClick:function(){
            var desc = (document.getElementById('kdp-desc')||{}).value || '';
            var keywords = (document.getElementById('kdp-keywords')||{}).value || '';
            var issues = [];
            if(cfg.title.length < 5) issues.push('Title too short (min 5 chars)');
            if(cfg.title.length > 200) issues.push('Title exceeds 200 chars');
            if(!cfg.subtitle) issues.push('Add a subtitle for better discoverability');
            if(desc.length < 50) issues.push('Description should be at least 50 chars');
            if(desc.length > 4000) issues.push('Description exceeds 4000 chars');
            var kwArr = keywords.split(',').map(function(k){return k.trim();}).filter(function(k){return k;});
            if(kwArr.length < 3) issues.push('Add at least 3 backend keywords');
            if(kwArr.length > 7) issues.push('Maximum 7 backend keywords allowed');
            if(issues.length) showToast(issues.join('. '), 'warn');
            else showToast('Listing looks great! All fields within KDP limits.', 'success');
          }}, 'Validate Listing')
        )
      )
    );

    var nicheContent = h('div', {key:'niche'},
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Word Bank Browser'),
        h('div', {className:'sec-bd'},
          h('div', {className:'chips', style:{marginBottom:8}},
            wordBankNames.slice(0,12).map(function(n){
              return h('span', {key:n, className:'chip'+(currentTheme===n?' on':''), onClick:function(){
                var bank = (window.WORD_BANKS||[]).find(function(b){return b.n===n;});
                if(bank){ setCurrentTheme(n); setWordText(bank.w.join('\n')); }
              }}, n);
            })
          ),
          h('div', {className:'info'}, (window.WORD_BANKS||[]).length + ' word banks available with ' + (window.WORD_BANKS||[]).reduce(function(s,b){return s+b.w.length;},0) + ' total words')
        )
      ),
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Word List Tools'),
        h('div', {className:'sec-bd'},
          h('div', {style:{display:'flex',gap:4,flexWrap:'wrap'}},
            h('button', {className:'btn btn-sec', onClick:function(){
              if(window.MXDWordListTools && window.MXDWordListTools.shuffle){
                var words = parseWords(wordText);
                setWordText(window.MXDWordListTools.shuffle(words).join('\n'));
                showToast('Words shuffled', 'info');
              }
            }}, 'Shuffle'),
            h('button', {className:'btn btn-sec', onClick:function(){
              var words = parseWords(wordText);
              var unique = words.filter(function(w,i,a){return a.indexOf(w)===i;});
              setWordText(unique.join('\n'));
              showToast('Removed ' + (words.length-unique.length) + ' duplicates', 'info');
            }}, 'Deduplicate'),
            h('button', {className:'btn btn-sec', onClick:function(){
              if(window.MXDWordListTools && window.MXDWordListTools.sortByLength){
                var words = parseWords(wordText);
                setWordText(window.MXDWordListTools.sortByLength(words, true).join('\n'));
                showToast('Sorted by length', 'info');
              }
            }}, 'Sort Length'),
            h('button', {className:'btn btn-sec', onClick:function(){
              var words = parseWords(wordText);
              setWordText(words.sort().join('\n'));
              showToast('Sorted A-Z', 'info');
            }}, 'Sort A-Z'),
            h('button', {className:'btn btn-sec', onClick:function(){
              if(window.MXDWordListTools && window.MXDWordListTools.getStats){
                var words = parseWords(wordText);
                var stats = window.MXDWordListTools.getStats(words);
                showToast('Words: ' + stats.count + ' | Avg length: ' + stats.avgLength + ' | Unique letters: ' + stats.uniqueLetters, 'info');
              } else {
                var words = parseWords(wordText);
                var avg = words.reduce(function(s,w){return s+w.length;},0) / (words.length||1);
                showToast('Words: ' + words.length + ' | Avg length: ' + avg.toFixed(1), 'info');
              }
            }}, 'Stats')
          )
        )
      ),
      h('div', {className:'sec'},
        h('div', {className:'sec-hd'}, h('span', {className:'sec-ttl'}), 'Categories'),
        h('div', {className:'sec-bd'},
          (window.CATEGORY_DB || []).map(function(cat){
            return h('div', {key:cat.id, className:'cat-item', style:{marginBottom:4}},
              h('div', {className:'cat-name'}, cat.n),
              h('div', {className:'cat-path'}, cat.path)
            );
          })
        )
      )
    );

    var tabContent = null;
    switch(tab){
      case 'settings': tabContent = h('div', null, settingsContent, quickSettings, advancedSettings); break;
      case 'niche': tabContent = nicheContent; break;
      case 'kdp': tabContent = kdpContent; break;
      case 'bulk': tabContent = bulkContent; break;
      case 'export': tabContent = exportContent; break;
      case 'play': tabContent = playContent; break;
      case 'presets': tabContent = presetsContent; break;
      case 'svg': tabContent = svgContent; break;
      case 'cover': tabContent = coverContent; break;
      case 'listopt': tabContent = listOptContent; break;
      default: tabContent = h('div', {className:'info'}, 'Select a tab');
    }

    return h('div', {className:'app'},
      h(DragonBG),
      toast ? h(Toast, {msg:toast.message, type:toast.type}) : null,
      h('div', {className:'workspace'},
        h('aside', {className:'sb'},
        h('div', {className:'sb-hd'},
          h('div', {className:'sb-logo'}, '\uD83D\uDD0D'),
          h('div', {className:'sb-brand'},
            h('h1', null, 'MXD Supreme Pro'),
            h('span', null, 'KDP Publishing Suite')
          )
        ),
        iconBar,
        h('div', {className:'sb-body'}, tabContent),
        h('div', {className:'sb-foot'},
          generating && progress ? h(Progress, {done:progress.done, total:progress.total, label:progress.label}) : null,
          h('div', {style:{display:'flex',alignItems:'center',gap:'6px',marginTop:'6px',fontSize:'10px',color:'var(--t3)'}},
            h('span', {style:{width:'8px',height:'8px',borderRadius:'50%',background:connDegraded?'#f59e0b':isOnline?'#10b981':'#ef4444',display:'inline-block',flexShrink:'0'}}),
            h('span', null, connDegraded ? 'Slow' : isOnline ? 'Online' : 'Offline'),
            puzzles.length > 0 ? h('span', {style:{marginLeft:'auto'}}, puzzles.length + ' puzzle(s)') : null
          )
        )
      ),
        h('main', {className:'main'},
          h('div', {className:'pza', style:{background:normalizedTmpl.bg}},
            h('div', {className:'pzc', style:{background:normalizedTmpl.bg, color:normalizedTmpl.tc, border:normalizedTmpl.borderStyle, fontFamily:normalizedTmpl.ff}},
              h('input', {className:'pz-t', value:cfg.title,
                onChange:function(e){setCfg(function(p){return Object.assign({},p,{title:e.target.value});});},
                style:{color:normalizedTmpl.tc, fontFamily:normalizedTmpl.ff}}),
              h(PuzzleGrid, {grid:(puzzles[page]||{}).grid||[], mask:(puzzles[page]||{}).mask||[], placements:(puzzles[page]||{}).placements||{},
                showSol:view==='solution', solStyle:cfg.solutionStyle,
                foundWords:foundWords, hlColor:cfg.highlightColor,
                fontWeight:cfg.fontWeight, cellSize:cfg.cellSize,
                onMouseDown:onMouseDown, onMouseEnter:onMouseEnter, onMouseUp:onMouseUp,
                selCells:selCells, template:normalizedTmpl, cfg:Object.assign({},cfg,{
                  fontFamily:normalizedTmpl.ff,
                  fontColor:normalizedTmpl.tc,
                  backgroundColor:normalizedTmpl.bg,
                  accentColor:normalizedTmpl.cc,
                  decorations: normalizedTmpl.decorations
                 })
                }),
              puzzles.length > 0 ? h('div', {style:{display:'flex',alignItems:'center',justifyContent:'center',gap:'8px',marginTop:'16px',flexWrap:'wrap'}},
                page > 0 ? h('button', {className:'btn btn-sec', onClick:function(){setPage(page-1);setFoundWords([]);setSelCells([]);setView('puzzle');}}, '\u25C0 Prev') : null,
                h('span', {style:{fontSize:'12px',fontWeight:'600',color:'var(--t2)',minWidth:'120px',textAlign:'center'}}, 'Puzzle ' + (page+1) + ' of ' + puzzles.length),
                page < puzzles.length - 1 ? h('button', {className:'btn btn-sec', onClick:function(){setPage(page+1);setFoundWords([]);setSelCells([]);setView('puzzle');}}, 'Next \u25B6') : null,
                h('button', {className:'btn', style:{background:view==='solution'?'var(--accent)':'var(--bg)',color:view==='solution'?'#fff':'var(--t1)',border:'1px solid var(--border)',borderRadius:'6px',padding:'6px 14px',fontSize:'12px',fontWeight:'600',cursor:'pointer'}, onClick:function(){setView(view==='solution'?'puzzle':'solution');}}, view==='solution'?'Hide Solution':'Show Solution')
              ) : null,
              window.AI_THEMES ? h('button', {className:'chip', onClick:function(){
                var k = Object.keys(window.AI_THEMES);
                var next = k[Math.floor(Math.random()*k.length)];
                setCurrentTheme(next);
                setWordText(window.AI_THEMES[next].join('\n'));
              }}, '\uD83C\uDFB2 Random Theme') : null
            )
          )
        )
      )
    );
  };

  window.App = App;
  console.log('[MXD App] Component registered with 10 navigation tabs');
})();
